server:
  package: api
  out: internal/adapters/api/server.gen.go
  generate:
    # implement server handlers manually with Fiber for now
    embedded-spec: true

types:
  package: models
  out: internal/domain/models/models.gen.go
  generate:
    types: true
    skip-prune: true

client:
  package: client
  out: internal/adapters/client/client.gen.go
  generate:
    client: true
