// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package models

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	OAuth2Scopes = "OAuth2.Scopes"
)

// Defines values for ExerciseDifficulty.
const (
	Advanced     ExerciseDifficulty = "advanced"
	Beginner     ExerciseDifficulty = "beginner"
	Intermediate ExerciseDifficulty = "intermediate"
)

// Defines values for ExerciseMuscleGroups.
const (
	Arms      ExerciseMuscleGroups = "arms"
	Back      ExerciseMuscleGroups = "back"
	Cardio    ExerciseMuscleGroups = "cardio"
	Chest     ExerciseMuscleGroups = "chest"
	Core      ExerciseMuscleGroups = "core"
	FullBody  ExerciseMuscleGroups = "fullBody"
	Legs      ExerciseMuscleGroups = "legs"
	Shoulders ExerciseMuscleGroups = "shoulders"
)

// Defines values for ProgressMetricMetricType.
const (
	ArmSize    ProgressMetricMetricType = "armSize"
	BodyFat    ProgressMetricMetricType = "bodyFat"
	ChestSize  ProgressMetricMetricType = "chestSize"
	Custom     ProgressMetricMetricType = "custom"
	LegSize    ProgressMetricMetricType = "legSize"
	MuscleMass ProgressMetricMetricType = "muscleMass"
	WaistSize  ProgressMetricMetricType = "waistSize"
	Weight     ProgressMetricMetricType = "weight"
)

// Defines values for WorkoutStatus.
const (
	Completed  WorkoutStatus = "completed"
	InProgress WorkoutStatus = "in_progress"
	Planned    WorkoutStatus = "planned"
	Skipped    WorkoutStatus = "skipped"
)

// Exercise defines model for Exercise.
type Exercise struct {
	Description  *string                 `json:"description,omitempty"`
	Difficulty   *ExerciseDifficulty     `json:"difficulty,omitempty"`
	Id           *openapi_types.UUID     `json:"id,omitempty"`
	Instructions *string                 `json:"instructions,omitempty"`
	MediaUrls    *[]string               `json:"mediaUrls,omitempty"`
	MuscleGroups *[]ExerciseMuscleGroups `json:"muscleGroups,omitempty"`
	Name         *string                 `json:"name,omitempty"`
}

// ExerciseDifficulty defines model for Exercise.Difficulty.
type ExerciseDifficulty string

// ExerciseMuscleGroups defines model for Exercise.MuscleGroups.
type ExerciseMuscleGroups string

// ProgressMetric defines model for ProgressMetric.
type ProgressMetric struct {
	Date       *time.Time                `json:"date,omitempty"`
	Id         *openapi_types.UUID       `json:"id,omitempty"`
	MetricType *ProgressMetricMetricType `json:"metricType,omitempty"`
	Notes      *string                   `json:"notes,omitempty"`
	Unit       *string                   `json:"unit,omitempty"`
	UserId     *openapi_types.UUID       `json:"userId,omitempty"`
	Value      *float32                  `json:"value,omitempty"`
}

// ProgressMetricMetricType defines model for ProgressMetric.MetricType.
type ProgressMetricMetricType string

// User defines model for User.
type User struct {
	CreatedAt      *time.Time           `json:"createdAt,omitempty"`
	Email          *openapi_types.Email `json:"email,omitempty"`
	FirstName      *string              `json:"firstName,omitempty"`
	Id             *openapi_types.UUID  `json:"id,omitempty"`
	LastName       *string              `json:"lastName,omitempty"`
	ProfilePicture *string              `json:"profilePicture,omitempty"`
	UpdatedAt      *time.Time           `json:"updatedAt,omitempty"`
	Username       *string              `json:"username,omitempty"`
}

// Workout defines model for Workout.
type Workout struct {
	ActualStartTime     *time.Time          `json:"actualStartTime,omitempty"`
	CreatedAt           *time.Time          `json:"createdAt,omitempty"`
	Description         *string             `json:"description,omitempty"`
	EndTime             *time.Time          `json:"endTime,omitempty"`
	Id                  *openapi_types.UUID `json:"id,omitempty"`
	Notes               *string             `json:"notes,omitempty"`
	PlannedStartTime    *time.Time          `json:"plannedStartTime,omitempty"`
	Sets                *[]WorkoutSet       `json:"sets,omitempty"`
	Status              *WorkoutStatus      `json:"status,omitempty"`
	Title               *string             `json:"title,omitempty"`
	TotalCaloriesBurned *float32            `json:"totalCaloriesBurned,omitempty"`
	UpdatedAt           *time.Time          `json:"updatedAt,omitempty"`
	UserId              *openapi_types.UUID `json:"userId,omitempty"`
}

// WorkoutStatus defines model for Workout.Status.
type WorkoutStatus string

// WorkoutPlan defines model for WorkoutPlan.
type WorkoutPlan struct {
	CreatedAt   *time.Time `json:"createdAt,omitempty"`
	Description *string    `json:"description,omitempty"`

	// Duration Duration in days
	Duration  *int                `json:"duration,omitempty"`
	Id        *openapi_types.UUID `json:"id,omitempty"`
	IsActive  *bool               `json:"isActive,omitempty"`
	Title     *string             `json:"title,omitempty"`
	TrainerId *openapi_types.UUID `json:"trainerId"`
	UpdatedAt *time.Time          `json:"updatedAt,omitempty"`
	UserId    *openapi_types.UUID `json:"userId,omitempty"`
	Workouts  *[]Workout          `json:"workouts,omitempty"`
}

// WorkoutSet defines model for WorkoutSet.
type WorkoutSet struct {
	Completed *bool `json:"completed,omitempty"`

	// Duration Duration in seconds for timed exercises
	Duration   *int                `json:"duration,omitempty"`
	ExerciseId *openapi_types.UUID `json:"exerciseId,omitempty"`
	Id         *openapi_types.UUID `json:"id,omitempty"`
	Reps       *int                `json:"reps,omitempty"`

	// RestTime Rest time after this set in seconds
	RestTime *int     `json:"restTime,omitempty"`
	Weight   *float32 `json:"weight,omitempty"`
}

// GetExercisesParams defines parameters for GetExercises.
type GetExercisesParams struct {
	MuscleGroup *string `form:"muscleGroup,omitempty" json:"muscleGroup,omitempty"`
	Difficulty  *string `form:"difficulty,omitempty" json:"difficulty,omitempty"`
	Query       *string `form:"query,omitempty" json:"query,omitempty"`
}

// GetProgressParams defines parameters for GetProgress.
type GetProgressParams struct {
	UserId     *openapi_types.UUID `form:"userId,omitempty" json:"userId,omitempty"`
	MetricType *string             `form:"metricType,omitempty" json:"metricType,omitempty"`
	StartDate  *openapi_types.Date `form:"startDate,omitempty" json:"startDate,omitempty"`
	EndDate    *openapi_types.Date `form:"endDate,omitempty" json:"endDate,omitempty"`
}

// GetWorkoutPlansParams defines parameters for GetWorkoutPlans.
type GetWorkoutPlansParams struct {
	UserId   *openapi_types.UUID `form:"userId,omitempty" json:"userId,omitempty"`
	IsActive *bool               `form:"isActive,omitempty" json:"isActive,omitempty"`
}

// GetWorkoutsParams defines parameters for GetWorkouts.
type GetWorkoutsParams struct {
	UserId    *openapi_types.UUID `form:"userId,omitempty" json:"userId,omitempty"`
	Status    *string             `form:"status,omitempty" json:"status,omitempty"`
	StartDate *openapi_types.Date `form:"startDate,omitempty" json:"startDate,omitempty"`
	EndDate   *openapi_types.Date `form:"endDate,omitempty" json:"endDate,omitempty"`
}

// PostExercisesJSONRequestBody defines body for PostExercises for application/json ContentType.
type PostExercisesJSONRequestBody = Exercise

// PostProgressJSONRequestBody defines body for PostProgress for application/json ContentType.
type PostProgressJSONRequestBody = ProgressMetric

// PostUsersJSONRequestBody defines body for PostUsers for application/json ContentType.
type PostUsersJSONRequestBody = User

// PutUsersUserIdJSONRequestBody defines body for PutUsersUserId for application/json ContentType.
type PutUsersUserIdJSONRequestBody = User

// PostWorkoutPlansJSONRequestBody defines body for PostWorkoutPlans for application/json ContentType.
type PostWorkoutPlansJSONRequestBody = WorkoutPlan

// PostWorkoutsJSONRequestBody defines body for PostWorkouts for application/json ContentType.
type PostWorkoutsJSONRequestBody = Workout

// PutWorkoutsWorkoutIdJSONRequestBody defines body for PutWorkoutsWorkoutId for application/json ContentType.
type PutWorkoutsWorkoutIdJSONRequestBody = Workout
